apiVersion: controlplane.cluster.x-k8s.io/v1alpha1
kind: VngCloudControlPlane
metadata:
  creationTimestamp: "2024-11-04T07:38:52Z"
  generation: 1
  labels:
    cluster.x-k8s.io/cluster-name: k8s-16464cd4-b09a-43b2-bc64-c9e7b26ebf2e
  name: k8s-16464cd4-b09a-43b2-bc64-c9e7b26ebf2e
  namespace: user-11412
  ownerReferences:
  - apiVersion: cluster.x-k8s.io/v1beta1
    blockOwnerDeletion: true
    controller: true
    kind: Cluster
    name: k8s-16464cd4-b09a-43b2-bc64-c9e7b26ebf2e
    uid: b82f11eb-50ec-42b4-bbe4-61401256d9cb
  resourceVersion: "181722481"
  uid: 4b78fe8a-5a42-488c-8c0c-003478a0ae36
spec:
  addons:
    konnectivity:
      agent:
        image: vcr.vngcloud.vn/81-vks-public/proxy-agent
        tolerations:
        - operator: Exists
        version: v0.0.32
      server:
        extraArgs:
        - --delete-existing-uds-file=true
        image: vcr.vngcloud.vn/81-vks-public/proxy-server
        port: 8132
        resources:
          limits:
            cpu: 100m
            memory: 200Mi
        version: v0.0.32
    kubeProxy:
      imageRepository: vcr.vngcloud.vn/81-vks-public
      imageTag: v1.29.1
  apiServer:
    extraArgs:
    - --cloud-provider=external
    resources:
      limits:
        cpu: 500m
        memory: 1000Mi
  controllerManager:
    extraArgs:
    - --cloud-provider=external
    resources:
      limits:
        cpu: 100m
        memory: 200Mi
  dataStoreName: ds-11b0971f-eb2f-49ec-8d3d-36581f0f8407
  deployment:
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - podAffinityTerm:
            labelSelector: 
              matchLabels:
                cluster.x-k8s.io/cluster-name: k8s-16464cd4-b09a-43b2-bc64-c9e7b26ebf2e
            topologyKey: kubernetes.io/hostname
          weight: 30
    additionalMetadata:
      labels:
        cluster.x-k8s.io/cluster-name: k8s-16464cd4-b09a-43b2-bc64-c9e7b26ebf2e
    podAdditionalMetadata:
      labels:
        cluster.x-k8s.io/cluster-name: k8s-16464cd4-b09a-43b2-bc64-c9e7b26ebf2e
  kubelet:
    cgroupfs: systemd
    preferredAddressTypes:
    - ExternalIP
    - InternalIP
    - Hostname
  network:
    serviceAnnotations:
      vks.vngcloud.vn/cluster-id: k8s-16464cd4-b09a-43b2-bc64-c9e7b26ebf2e
      vks.vngcloud.vn/listener-allowed-cidrs: '{"cidrs":[{"ip-address":"0.0.0.0","subnet-mask":"0"}]}'
      vks.vngcloud.vn/spare-pool: workload-clusters
    serviceType: LoadBalancer
  registry: vcr.vngcloud.vn/81-vks-public
  replicas: 3
  scheduler:
    resources:
      limits:
        cpu: 100m
        memory: 200Mi
  version: v1.29.1
status:
  conditions:
  - lastTransitionTime: "2024-11-04T07:38:53Z"
    message: ""
    observedGeneration: 1
    reason: Succeeded
    status: "True"
    type: TenantControlPlaneCreated
  - lastTransitionTime: "2024-11-04T07:38:55Z"
    message: ""
    observedGeneration: 1
    reason: Succeeded
    status: "True"
    type: TenantControlPlaneAddressReady
  - lastTransitionTime: "2024-11-04T07:38:55Z"
    message: ""
    observedGeneration: 1
    reason: Succeeded
    status: "True"
    type: InfrastructureClusterPatched
  - lastTransitionTime: "2024-11-04T07:38:58Z"
    message: ""
    observedGeneration: 1
    reason: Succeeded
    status: "True"
    type: VngCloudControlPlaneIsInitialized
  - lastTransitionTime: "2024-11-04T07:38:58Z"
    message: ""
    observedGeneration: 1
    reason: Succeeded
    status: "True"
    type: KubeadmResourcesCreated
  - lastTransitionTime: "2024-11-04T07:39:32Z"
    message: ""
    observedGeneration: 1
    reason: Succeeded
    status: "True"
    type: VngCloudControlPlaneIsReady
  externalManagedControlPlane: true
  initialized: true
  ready: true
  readyReplicas: 3
  replicas: 3
  selector: cluster.x-k8s.io/cluster-name=k8s-16464cd4-b09a-43b2-bc64-c9e7b26ebf2e
  unavailableReplicas: 0
  updatedReplicas: 3
  version: v1.29.1
